### ISSUE TITLE
How do I use the coordinate function of proximity?

### ISSUE THREAD

**Issue by hsiang051** [eldoriarpg/BigDoorOpener#22]
![image](https://user-images.githubusercontent.com/41193849/87784542-1785fe00-c869-11ea-87e6-35f1dea67dd4.png)

**Comment by RainbowDashLabs** [comment]
The proximity function is radial around the center of the door.

The door center is calculated by the BDO. So you use coordinates relative to the door.
You just have to set the radius in around the door.

For example a cuboid region around the door center with height 10 and the radius 20 would be
/bdo setCondition 6 proximity 20,10,20 cuboid.

I will make the wiki clearer in this point.

**Comment by hsiang051** [comment]
I have another question
![image](https://user-images.githubusercontent.com/41193849/87786901-59b13e80-c86d-11ea-8230-83d2844c42f1.png)

<time>

**Comment by RainbowDashLabs** [comment]
Thats from bigdoors.
The syntax should be  /SetBlocksToMove <doorUID> <blocksToMove> and not time.

Will ask pim about it.
