### ISSUE TITLE
Add Mythicmobs support,it may be cool for RPG servers

### ISSUE THREAD

**Issue by Sannnnnd** [eldoriarpg/BigDoorOpener#31]
The door open after a set mob from mythicmobs be killed,so player can get access to the next level

**Comment by RainbowDashLabs** [comment]
I will include this in the next version. Thanks for your suggestion.

https://mythicmobs.net/manual/doku.php/api

**Comment by RainbowDashLabs** [comment]
How would you prefer to select the mob? I never used this plugin. How is the solution of other plugins?

Do they use the display name of the mob? Would be easier if you had filled out the feature request template tho...

**Comment by Sannnnnd** [comment]
This is the quest plugin i use in my server,it supports mythicmobs and it uses mythicmobtype (mob id) instead of display name
https://wiki.electro2560.com/cluescrolls/clue-creation

**Comment by RainbowDashLabs** [comment]
Okay I will use this too then I guess.

**Comment by RainbowDashLabs** [comment]
I published the build with mythic mob integration on spigot:
https://www.spigotmc.org/resources/big-doors-opener.80805/
