### ISSUE TITLE
[BUG] MythicMobs compatibility broke in latest releases

### ISSUE THREAD

**Issue by Brickwrath** [eldoriarpg/BigDoorOpener#61]
Big Doors Opener Version: 2.4.5
Big Doors Version: Alpha 0.1.8.37
MythicMobs: Latest Dev (5.0.0+)

**Problem**
Console Error Message on server startup
```
[BigDoorsOpener] Plugin BigDoorsOpener v2.4.5 has failed to register events for class de.eldoria.bigdoorsopener.conditions.standalone.mythicmobs.MythicMobsListener because io/lumine/xikage/mythicmobs/api/bukkit/events/MythicMobDeathEvent does not exist.
```

**Additional context**
I'm assuming the recent MythicMobs API rewrite is causing this.
Figured I'd let report it just in case it hasn't been mentioned yet.

**Comment by RainbowDashLabs** [comment]
Hey. Sorry for the late reply.
I looked into it, but Mythic already failed with updating their plugin documentation. Also they do not provide any never version than 4.9.1 in their repositories I know of MythicMobs.
I will wait now of an answer from the mythic devs. But they showed little to no motivation in making it easy for devs to integrate their plugin,

**Comment by RainbowDashLabs** [comment]
It is fixed on a feature branch. Since I dont have 5.x currently installed I would be grateful if you could check it out and report any issues with it.

https://eldonexus.de/repository/maven-snapshots/de/eldoria/bigdoorsopener/2.4.5-SNAPSHOT/bigdoorsopener-2.4.5-20220414.075945-1.jar
