### ISSUE TITLE
[Feature] Delay after Equip Gun before you can shoot

### ISSUE THREAD

**Issue by JaHollTV** [eldoriarpg/BigDoorOpener#99]
**Describe the solution you'd like**
When you switch to a weapon in your hotbar, before you can shoot there is a global delay – set in config.yml

**Additional context**
It's great for RPG. That you can not switch to a weapon and instantly shoot.

**Comment by RainbowDashLabs** [comment]
Are you sure you are requesting this feature at the right plugin?

**Comment by JaHollTV** [comment]
omg i am so sorry!
